### ISSUE TITLE
Cannot  Establishing connection

### ISSUE THREAD

**Issue by securylight** [mhewedy/vermin#10] opened 2020-08-10 08:52 UTC
Hi there,

created the file and ran it:

sudo apt update -y
sudo apt install redis-server -y
sudo sed -i 's/^supervised no/supervised systemd/' /etc/redis/redis.conf
sudo systemctl restart redis.service
sudo systemctl status redis

vermin create ubuntu/focal script.sh

the machine was created, I can see it.
but cannot establish a connection using:
 vermin ssh vm_01
windows10, vbox 6.1

Thanks!

**Comment by mhewedy** [comment] 2020-08-10 14:01
I will try to reproduce the issue. 
But for now can you tell me what is the result of `vermin ssh m_01`?

Also can you try the command `vermin ip vm_01 --purge`
And share the result with me

**Comment by securylight** [comment] 2020-08-10 14:17
Sure.
the result of   vermin ssh vm_01:
"Cannot establish connection."

have tried:
" vermin ip vm_01 --purge"
and got:
Cannot find ip for vm_01
Use the command 'vermin ip -p vm_01' to purge cache

ran:
vermin ip -p vm_01
got the same:
Cannot find ip for vm_01
Use the command 'vermin ip -p vm_01' to purge cache

**Comment by mhewedy** [comment] 2020-08-10 15:59
Thanks for the update.

Apparently the issue related to vermin cannot find the IP for the running VM.

Can I ask what is the subnet for your local network?

Also, could you execute the following: `vermin gui vm_01`

Then log in using username/password: vermin/vermin
Then inside the VM type `ip addr | grep inet` and report the assigned IP to me?


_To let you know what I am trying to do, currently, I have no access to a Windows machine, I am trying to utilize AWS bare metal instances to duplicate this issue._

**Comment by securylight** [comment] 2020-08-10 16:27
when I created the machine it was on bridge adapter.
it didn't work and actually i don't like bridge adapter at all. so I
changed to host only
the subnet is virtualbox's subnet.... 255.255.255.0
I got the same msg for the vermin gui command
but logged in using vbox directly and got this
[image: image.png]

there are free windows machines for testings if you like,
https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

Let me know if you need more help!
Good luck and take care.

**Comment by mhewedy** [comment] 2020-08-10 16:38
The point is, vermin uses a bridge adapter by default, and many commands including `ssh` and `ip` depend on that. (I find the bridge adapter more flexible others 😊 )

unfortunately, I don't think it gonna work on other networking settings. (at least the current version)

Can you try to reupload the image on GitHub directly (instead of sending via email) as it doesn't appear to show.

Thanks for your support regarding the Windows VMs, but actually I cannot run VirtualBox inside one of these VMs as it would require what so call "Nested Virtualizations" which is very hard to achieve. I tried it before and couldn't make it work.

Thanks.

**Comment by securylight** [comment] 2020-08-10 16:51
sure I'll do it.
the same error occurs with bridge and host-only.... the issue is somewhere
else...

**Comment by securylight** [comment] 2020-08-10 16:52
![image](https://user-images.githubusercontent.com/37718207/89808539-f7cdb700-db42-11ea-9bc3-6c0efa031d44.png)

**Comment by mhewedy** [comment] 2020-08-10 17:00
@securylight this screenshot when you are using the bridge mode, correct?

**Comment by mhewedy** [comment] 2020-08-10 17:03
Also, can you execute this command please and return the output to me:

`VERMIN_DEBUG=true vermin ip -p vm_01`

**Comment by securylight** [comment] 2020-08-10 17:28
> @securylight this screenshot when you are using the bridge mode, correct?
this is host only. with bridge,  instead of 56, 1.

**Comment by securylight** [comment] 2020-08-10 17:29
> Also, can you execute this command please and return the output to me:
> 
> `VERMIN_DEBUG=true vermin ip -p vm_01`

'VERMIN_DEBUG' is not recognized as an internal or external command,
operable program or batch file.

**Comment by mhewedy** [comment] 2020-08-10 17:48
> > Also, can you execute this command please and return the output to me:
> > `VERMIN_DEBUG=true vermin ip -p vm_01`
> 
> 'VERMIN_DEBUG' is not recognized as an internal or external command,
> operable program or batch file.

This is a  *nix only syntax, which I think will not work on windows, so can you try instead:

```
set VERMIN_DEBUG=true
vermin ip -p vm_01
```
But you need to make the VM work in bridge network mode first.

**Comment by securylight** [comment] 2020-08-11 06:54
I switch networking to bridge and the vm_01 got the address from my home network 192.168.1.0/24.

when running vermin ip -p vm_01 with vermin_debug = true,
there is a ping to all addresses in the virtual box network: 192.168.56.0/24
There is no ping of course and there is a msg: Cannot find ip for vm_01

bottom line, the scanned  network that is the Virtualbox internal network and not the real one

**Comment by mhewedy** [comment] 2020-08-11 12:04
I did some more investigation in the problem (I used some windows bare metal server from AWS to duplicate your issue), and I knew the root cause and pushed a fix today.

The fix I pushed just skip the VirtualBox network from scanning while trying to get the IP address from the VM. 

I think It should work just fine for you in the bridge settings ... Can you please check and let me know your feedback?

To get the latest version just use the same installation script, it will do the upgrade for you.
To make sure you have the latest version run:

```
$ vermin -v
vermin version v0.90.0
```

**Comment by securylight** [comment] 2020-08-11 12:33
I've taken the latest version, and now vermin ping this network:
192.168.92.0/24 for some reason.
I get the same message of course:
Cannot establish a connection.

**Comment by mhewedy** [comment] 2020-08-11 15:42
@securylight 
I really appreciate your patience.

I have released a new version (**v0.91.0**) with a relatively [big commit](https://github.com/mhewedy/vermin/commit/a15dc84d780663aed5eaeb7b9ee982bbd24703d3). It fixes some issues related to `arp`ing and `ping`ing that I hope it fixes your issue this time. (it now uses all network interfaces instead of just one - as in your case)

Please try to create a new VM and let me know your feedback.

Thanks.

**Comment by securylight** [comment] 2020-08-11 19:24
Sure, no problem.

I'm sorry but it doesn't help. it pings loopback and link-local subnets and eventually the result is the same

**Comment by mhewedy** [comment] 2020-08-11 20:29
> Sure, no problem.
> 
> I'm sorry but it doesn't help. it pings loopback and link-local subnets and eventually the result is the same

What you mean by "link-local" subnets ?

**Comment by securylight** [comment] 2020-08-11 21:16
169.254.X.X

בתאריך יום ג׳, 11 באוג׳ 2020, 11:29 PM, מאת Muhammad Hewedy ‏<
notifications@github.com>:

**Comment by mhewedy** [comment] 2020-08-12 08:28
please run `arp -a` in your command line and share the whole result as is with me.

**Comment by mhewedy** [comment] 2020-08-12 08:32
Also share the result of `vermin create` with me enabling the debugging, share the run result as is.

**Comment by securylight** [comment] 2020-08-12 09:07
sorry, that's not an option, can't share with you these details.
the output reflects the vbox,  vmware, and my home networks.
I've disabled the vmware network card but the script consumes tons of CPU
and I must work, I'll try again at night.

**Comment by anand6998** [comment] 2020-10-03 20:23
I am having the same issue - Vermin can only create one VM. From what I see - when I start vm_02 VM it gets the same IP address as vm_01. Is there a fix for this issue yet.

**Comment by mhewedy** [comment] 2020-10-03 21:00
> I am having the same issue - Vermin can only create one VM. From what I see - when I start vm_02 VM it gets the same IP address as vm_01. Is there a fix for this issue yet.

So the first VM is created, but the second fails? 

which os you are using?

**Comment by anand6998** [comment] 2020-10-03 21:48
Hi Muhammad

Both VM’s are created but vermin is only able to connect to the first one.

(base) 5c40d7c:redis-vm anand$ vermin ip vm_01
192.168.86.33

(base) 5c40d7c:redis-vm anand$ vermin ip vm_02
Cannot find ip for vm_02
Use the command 'vermin ip -p vm_02' to purge cache
(base) 5c40d7c:redis-vm anand$ vermin ip -p vm_02
Cannot find ip for vm_02
Use the command 'vermin ip -p vm_02' to purge cache

VM NAME        IMAGE                                   CPUS      MEM       DISK         TAGS
vm_01          ubuntu/focal                            1         1024      2.8GB        
vm_02          ubuntu/focal                            1         1024      2.8GB       

(base) 5c40d7c:redis-vm anand$ vermin ssh vm_01
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Sat 03 Oct 2020 09:40:45 PM UTC

  System load:  0.0               Processes:               105
  Usage of /:   44.1% of 9.78GB   Users logged in:         1
  Memory usage: 22%               IPv4 address for enp0s3: 192.168.86.33
  Swap usage:   0%


3 updates can be installed immediately.
0 of these updates are security updates.
To see these additional updates run: apt list --upgradable


Last login: Sat Oct  3 21:37:53 2020 from 192.168.86.30


(base) 5c40d7c:redis-vm anand$ vermin ssh vm_02
✔ Establishing connection  
Cannot establish connection.


When I connect directly from VirtualBox
I see both VM’s have the same IP address

Hope this information helps

Regards

**Closed** 2024-04-04 11:21 UTC
